config/routes.rb
Rails.application.routes.draw do

#Casein routes
namespace :casein do
    resources :inboxes
    resources :links
#    get ':slug' => 'casein/links#show'

end
    root 'casein/links#index'
    get '/casein' => 'casein/links#index'
    get ':slug' => 'redirect_url#index'
    get ':url' => 'casein/inboxes#new/:id'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inbox.rb
class Inbox < ApplicationRecord
	validates :shortmessage, presence: true
	validates :reseiver, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :casein_admin_users, optional: true

  baselink = 'http://54.187.194.9/'
  validates :slug, length: { maximum: 4 }, uniqueness: {
    message: ->(object, data) do 
      "#{ENV['BASE_URL']}#{data[:value]} allready enter and it`s long URL - #{Link.find_by_slug(object.slug).given_url}"
      
    end
  }
  validates :given_url, :format => URI::regexp(%w(http https)), allow_blank: true, uniqueness: {
    message: ->(object, data) do 
      " \"#{data[:value]}\" has allready been shorten URL - \"#{ENV['BASE_URL']}#{Link.find_by_given_url(object.given_url).slug}\", of user #{Casein::AdminUser.find(object.casein_admin_users_id).name}"
      
    end
  }
  after_create :generate_slug

  def generate_slug
    #self.slug = self.title if self.title
    self.slug = Random.rand(77778888).to_s(36)[0..3] if self.slug == ""
    # if Link.find_by_slug(self.slug)
    # 	self.given_url = Link.find_by_slug(self.slug).given_url
    #  end
    #  self.clicks = Link.find_by_given_url(self.given_url).id
    #  self.slug = Link.find(self.clicks).slug if self.clicks != self.id
         
    agent = Mechanize.new
    page = agent.get(self.given_url)
    self.title = page.title
    #casein_admin_users_id = current_user.id
      
    self.save
    
  end

  def display_slug
   "http://54.187.194.9/" + self.slug.to_s
  end

    def perform(link_id)

  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :links, dependent: :destroy
  #devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
  # acts_as_messageable

  # def mailboxer_name
  #   self.email
  # end

  # def mailboxer_email(object)
  #   self.email
  # end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/casein/inboxes_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class InboxesController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    # before_action :needs_admin_or_current_user, only: [:action1, :action2]
  
    def index
      @casein_page_title = 'Inboxes'
      @inboxes = Inbox.order(sort_order(:shortmessage)).paginate page: params[:page]
    end

    def show
      @casein_page_title = 'View inbox'
      @inbox = Inbox.find params[:id]
      @inbox.read = 0
      @inbox.save
      @url = @inbox.shortmessage
    end

    def new
      @url = Link.find(params[:url]).display_slug
      @casein_page_title = 'Add a new inbox'
      @inbox = Inbox.new
    end

    def create
      @inbox = Inbox.new inbox_params
      @inbox.sender = current_user.id

      if @inbox.save
        flash[:notice] = 'Inbox created'
        redirect_to casein_inboxes_path
      else
        flash.now[:warning] = 'There were problems when trying to create a new inbox'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update inbox'

      @inbox = Inbox.find params[:id]

      if @inbox.update_attributes inbox_params
        flash[:notice] = 'Inbox has been updated'
        redirect_to casein_inboxes_path
      else
        flash.now[:warning] = 'There were problems when trying to update this inbox'
        render action: :show
      end
    end

    def destroy
      @inbox = Inbox.find params[:id]

      @inbox.destroy
      flash[:notice] = 'Inbox has been deleted'
      redirect_to casein_inboxes_path
    end

    private

    def inbox_params
      params.require(:inbox).permit(:shortmessage, :sender, :reseiver, :read, :url)
    end
  end
end

app/controllers/casein/links_controller.rb
# Scaffolding generated by Casein v5.2.0.0

module Casein
  class LinksController < Casein::CaseinController
    ## optional filters for defining usage according to Casein::AdminUser access_levels
    # before_action :needs_admin, except: [:action1, :action2]
    #before_action :needs_admin_or_current_user, except: [:index, :new, :create, :update, :destr]
  
    def index
      @casein_page_title = 'Links'
      @links = Link.order(sort_order(:given_url)).paginate page: params[:page]
    end

  def show
    if params[:slug]
      @link = Link.find_by(slug: params[:slug])
      if redirect_to @link.given_url
        @link.save
      end
    else
      @link = Link.find(params[:id])
    end
  end


    def new
      @casein_page_title = 'NEW Short'
      @link = Link.new
      Link.all.each {|i| i.destroy if Time.now.to_i - i.created_at.to_i >= 1296000 }
    end

    def create
      @link = Link.new link_params
      @link.casein_admin_users_id = current_user.id
      if @link.save
        flash[:notice] = 'You URL shorten!'
        redirect_to casein_links_path
      else
        flash.now[:warning] = 'There were problems when trying to short you link'
        render action: :new
      end
    end

    def update
      @casein_page_title = 'Update link'

      @link = Link.find params[:id]

      if @link.update_attributes link_params
        flash[:notice] = 'Link has been updated'
        redirect_to casein_links_path
      else
        flash.now[:warning] = 'There were problems when trying to update this link'
        render action: :show
      end
    end

    def destroy
      @link = Link.find params[:id]

      @link.destroy
      flash[:notice] = 'Link has been deleted'
      redirect_to casein_links_path
    end

    private

    def link_params
      params.require(:link).permit(:given_url, :slug, :title,)
    end
  end
end

app/controllers/redirect_url_controller.rb
class RedirectUrlController < ApplicationController
	  def index
      @links = Link.new
    	if params[:slug]
      		@link = Link.find_by(slug: params[:slug])
      	if redirect_to @link.given_url
        	@link.save
      	end
    	else
       @link = Link.find(params[:id])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/casein/config_helper.rb
module Casein
  module ConfigHelper
    
    # Name of website or client — used throughout Casein.
    def casein_config_website_name
      'URL Shortener'
    end

    # Filename of logo image. Ideally, it should be a transparent PNG around 140x30px
    def casein_config_logo
      'logo.png'
    end

    # The server hostname where Casein will run
    def casein_config_hostname
      if Rails.env.production?
        'http://www.caseincms.com'
      else
        'http://0.0.0.0:3000'
      end
    end

    # The sender address used for email notifications
    def casein_config_email_from_address
      'dbachinin@ya.ru'
    end
  
    # The initial page the user is shown after they sign in or click the logo. Probably this should be set to the first tab.
    # Do not point this at casein/index!
    def casein_config_dashboard_url
      url_for controller: :casein, action: :links
    end
  
    # A list of stylesheets to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_stylesheet_includes
      %w[casein/casein casein/custom]
    end
  
    # A list of JavaScript files to include. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_javascript_includes
      %w[casein/casein casein/custom]
    end

     # A list of stylesheets to include in the authentication layout. Do not remove the core casein/login, but you can change the load order, if required.
    def casein_config_auth_stylesheet_includes
      %w[casein/login casein/auth_custom]
    end
  
    # A list of JavaScript files to includein the authentication layout. Do not remove the core casein/casein, but you can change the load order, if required.
    def casein_config_auth_javascript_includes
      %w[casein/casein casein/auth_custom]
    end
    
  end
end

app/helpers/redirect_url_helper.rb
module RedirectUrlHelper
end

app/views/casein/inboxes/_form.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->


<div class="row">
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :shortmessage, {:value => @url} %>
  </div>



  <div class="col-lg-6">
     <%= casein_select f, f.object, :reseiver, Casein::AdminUser.order(:name).collect {|c| [c.name, c.id]}, {:include_blank => '-- None --', :casein_label => "Choose an existing reseiver"} %>
  </div>

</div>

app/views/casein/inboxes/_showform.html.erb
<div class=col-lg-6>
    <div class="text-center"><h1><%= link_to @url, @url %></h1></div>
    <p class="text-primary"><%= Link.find_by_slug(@url.last(4)).title %><p>
    </div>

app/views/casein/inboxes/_table.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th><%= casein_sort_link "Shared_URL", :shortmessage %></th>
      <th><%= casein_sort_link "Sender", :sender %></th>
      <th>&nbsp;</th>
    </tr>
  </thead>

  <% inboxes.each do |inbox|
    if inbox.reseiver == current_user.id
      shortmessage = inbox.shortmessage.last(4)
      sender = inbox.sender
   %>
    <tr>
      <td><%= casein_table_cell_link truncate(Link.find_by_slug(shortmessage).title, length: 30), casein_inbox_path(inbox) %></td>
      <td><%= casein_table_cell_link Casein::AdminUser.find(sender).name, casein_inbox_path(inbox) %></td>
       <td class="delete">
        <%= link_to(casein_show_row_icon("trash"), casein_inbox_path(inbox), method: :delete, data: { confirm: "Are you sure you want to delete this inbox?" }) %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/casein/inboxes/index.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Inbox<%= casein_pagination_details @inboxes %></h2>

<%= render partial: 'casein/inboxes/table', locals: { inboxes: @inboxes } %>

<div class="text-center">
  <%= will_paginate @inboxes %>
</div>

<%= content_for :sidebar do %>

  <li><%= link_to "#{casein_show_icon "plus-sign"}Add Short URL".html_safe, new_casein_link_path %></li>

<% end %>

app/views/casein/inboxes/new.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Add a new inbox</h2>

<%= form_for @inbox, url: casein_inboxes_path do |f| %>

  <%= render partial: 'casein/inboxes/form', locals: { f: f } %>

  <p class="submits">
    <%= link_to 'Cancel', casein_inboxes_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Add new inbox", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_inboxes_path %></li>
<% end %>

app/views/casein/inboxes/show.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Received URL</h2>

<%= form_for @inbox, url: casein_inbox_path(@inbox) do |f| %>

  <%= render partial: 'casein/inboxes/showform', locals: { f: f } %>

  <p class="submits">


    <%= link_to 'Back', casein_inboxes_path, class: 'btn btn-lg btn-primary' %>

  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_inboxes_path %></li>
<% end %>

app/views/casein/layouts/_tab_navigation.html.erb
<!-- NOTE: the casein:scaffold generator automatically appends new controllers to this file. The SCAFFOLD_INSERT line must NOT be removed -->
<!-- SCAFFOLD_INSERT -->
<%
inboxes = Inbox.all.where(reseiver: current_user)
count_inbox ||=0
count_inbox = inboxes.where(read: nil).count 
%>

<li id="tab-inboxes"><%= link_to "Inbox \(#{count_inbox}\)", casein_inboxes_path %></li>
<li id="tab-links"><%= link_to "Links", casein_links_path %></li>

app/views/casein/layouts/_top_navigation.html.erb
<!-- NOTE: add "hidden-xs hidden-sm" class to li elements you want to be hidden at small browser widths -->
<!-- e.g. <li class="hidden-xs hidden-sm"><%= link_to "Visit site", casein_config_hostname, target: "_blank" %></li> -->

<li><%= link_to "Visit site", casein_config_hostname, target: "_blank" %></li>

app/views/casein/links/_form.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->


<div class="row">
  <div class="col-lg-12">
   <%= casein_text_field f, f.object, :given_url %>
    
  </div>
</div>

<div class="row">
  <div class="col-lg-6">
   <%= casein_url_field f, f.object, :display_slug %>

  </div>
  <div class="col-lg-6">
    <%= casein_text_field f, f.object, :slug %>
  </div>
</div>

app/views/casein/links/_table.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
    <% userid = Casein::AdminUser.find(current_user.id) %>
     <%= userid.name %>

      <th><%= casein_sort_link "Title", :title %></th>
      <th><%= casein_sort_link "Slug", :slug %></th>
      <th><%= casein_sort_link "Given url", :given_url %></th>
      
      <th>&nbsp;</th>
    </tr>
  </thead>

  <% links.each do |link| 
    if link.casein_admin_users_id == current_user.id
    title = link.title 
    display_slug = link.display_slug 
    created_at = link.created_at 
    given_url = link.given_url 
    slug = link.slug 
     %>

    <tr>
      <td><h5 class="text-warning"><%= casein_table_cell_link truncate(link.title, length: 30), casein_link_path(link) %></h5></td>
      <td><code><%= casein_table_cell_link link.slug, casein_link_path(link) %></code></td>
      <td><%= casein_table_cell_link truncate(link.given_url, length: 30), casein_link_path(link) %></td>
      
      </td>
    </tr>
    <% end %>
  <% end %>
</table>

app/views/casein/links/index.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Links<%= casein_pagination_details @links %></h2>

<%= render partial: 'casein/links/table', locals: { links: @links } %>

<div class="text-center">
  <%= will_paginate @links %>
</div>

<%= content_for :sidebar do %>

  <li><%= link_to "#{casein_show_icon "plus-sign"}Add Short URL".html_safe, new_casein_link_path %></li>

<% end %>

app/views/casein/links/new.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>Add a new link</h2>

<%= form_for @link, url: casein_links_path do |f| %>

  <%= render partial: 'casein/links/form', locals: { f: f } %>
  <% @link.casein_admin_users_id = current_user.id %> 
  <p class="submits">
    <%= link_to 'Cancel', casein_links_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Shorten me", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_links_path %></li>
<% end %>

app/views/casein/links/show.html.erb
<!-- Scaffolding generated by Casein v5.2.0.0 -->

<h2>View link</h2>

<%= form_for @link, url: casein_link_path(@link) do |f| %>

  <%= render partial: 'casein/links/form', locals: { f: f } %>

  <p class="submits">
  <%= link_to 'Share', new_casein_inbox_path(:url => @link.id), class: 'btn btn-mini btn-success' %>
      <%= link_to 'Cancel', casein_links_path, class: 'btn btn-mini btn-danger' %>
    <%= f.submit "Save changes", class: "btn btn-mini btn-primary" %>
  </p>

<% end %>

<%= content_for :sidebar do %>
  <li><%= link_to "#{casein_show_icon "th-list"}Back to list".html_safe, casein_links_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyPortfolio2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>